### PR TITLE
Create PairSum.cpp

### PR DESCRIPTION
**Pull request by Jainsuhani2021**

### CODE REVIEW

**Comment by Jainsuhani2021** [comment]
@risingstar-bit sir please have a look

**Comment by Jainsuhani2021** [comment]
@risingstar-bit sir please assign this issue to me

**Comment by risingstar-bit** [comment]
> @risingstar-bit sir please assign this issue to me

Are you contributing for hacktoberfest or for just open source?

**Comment by Jainsuhani2021** [comment]
Sir for Hacktoberfest
Thank you sir

**Pull request merged**
