### PR TITLE
Create Searching algorithm

### PR DESCRIPTION
**Pull request by Tishachhabra**
This will search an element in array

### CODE REVIEW

**Comment by sudipg4112001** [comment]
Add readme file

**Comment by risingstar-bit** [comment]
> Done @sudipg4112001

put it in Algorithm folder

**Comment by Tishachhabra** [comment]
Is it okay now?

**Review by risingstar-bit — COMMENTED** [review]
@Tishachhabra Mention the algorithm name LinearSeacrh/BinarySearch. And in README file write its algorithm briefly

**Comment by risingstar-bit** [comment]
> @Tishachhabra Mention the algorithm name LinearSeacrh/BinarySearch. And in README file write its algorithm briefly

Follow these steps:

 DSA/JAVA/Algorithm/Searching should contains 2 folder- LinearSearch and BinarySearch and it these folder you need to add one source code file and README file respectivey

**Pull request closed without merging**
