### PR TITLE
Added Floyd’s Cycle Finding Algorithm for linked list under C++, Link…

### PR DESCRIPTION
**Pull request by purbendu**

### CODE REVIEW

**Comment by risingstar-bit** [comment]
@purbendu add README file for this algorithm

**Comment by sudipg4112001** [comment]
> _ No description provided. _

Also remove the file of VS Code

**Comment by purbendu** [comment]
Noted

**Comment by purbendu** [comment]
Made the above changes, kindly review

**Comment by sudipg4112001** [comment]
Paths for all the files are not correct @purbendu 
Please carefully make the corrections

**Pull request closed without merging**
