### PR TITLE
Data Science Roadmaps 

### PR DESCRIPTION
**Pull request by prateekj7777**
NLP roadmaps

### CODE REVIEW

**Comment by risingstar-bit** [comment]
@prateekj7777 please describe it too. Get the idea from other roadmaps present in the folder. Give valid file name.

**Comment by prateekj7777** [comment]
I will add a readme for this

**Comment by risingstar-bit** [comment]
> I will add a readme for this

yes

**Comment by prateekj7777** [comment]
Added a description file.

**Comment by sudipg4112001** [comment]
> Added a description file.

@prateekj7777 
You are putting files in incorrect format
Please make a proper folder for NLP roadmap with a readme file included in it.
Make make a different PR with the corrected format.

**Comment by prateekj7777** [comment]
Sure Will do

**Comment by prateekj7777** [comment]
Okay

**Pull request closed without merging**
