### PR TITLE
Create First missing positive integer.cpp

### PR DESCRIPTION
**Pull request by Jainsuhani2021**

### CODE REVIEW

**Comment by Jainsuhani2021** [comment]
@risingstar-bit sir please have a look

**Comment by risingstar-bit** [comment]
> @risingstar-bit sir please have a look

Put it in proper folder

**Comment by Jainsuhani2021** [comment]
@risingstar-bit sir actually i am new to open source will u please tell me how can i put it in a proper folder? please

**Comment by risingstar-bit** [comment]
> @risingstar-bit sir actually i am new to open source will u please tell me how can i put it in a proper folder? please

First fork this repo, then go to DSA folder choose your programming language to which you want to add your program then you will see varities of folder 📂. Choose appropriate one ex- you are adding first missing postive so go to leetcode problem section then go to file→select create new file →paste your source code and give proper name to your file. After that create new branch and pull request to your repository. You will find merge option so merge your PR to your repository. After merging into your repo go to code section in you will find 1/2 commit ahead depending on your files. Click on that make pull request after selecting your branch then I'll merge it.

**Comment by Jainsuhani2021** [comment]
ok thanku so much sir for your help. I will do it just now

**Comment by Jainsuhani2021** [comment]
sir i have just seen that someone already has contributed on this topic. so sorry sir i should have seen it earlier. sorry sir for the inconvenience

**Comment by risingstar-bit** [comment]
> sir i have just seen that someone already has contributed on this topic. so sorry sir i should have seen it earlier. sorry sir for the inconvenience

okay no problem.

**Pull request closed without merging**
